version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      time: "23:00"
      timezone: PST8PDT
    open-pull-requests-limit: 10
  - package-ecosystem: pip
    directory: "/examples"
    schedule:
      interval: weekly
      day: sunday
      time: "23:00"
      timezone: PST8PDT
    open-pull-requests-limit: 10
