name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [14, 16, 18]

    name: Node ${{ matrix.node }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup python
      - uses: actions/setup-python@v4
  	with:
    	  python-version: '3.10' 
      - run: python my_script.py

      - name: Change into examples directory
        run: cd examples

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate examples
        run: python example_plots.py
